export const DEFAULT_BACKEND_PORT = 4000;
export const DEFAULT_WEB_PORT = 3000;

export const DEFAULT_ACCESS_TOKEN_TTL = '15m';
export const DEFAULT_ACCESS_TOKEN_EXPIRES_IN_SECONDS = 15 * 60; // 900 seconds
export const DEFAULT_REFRESH_TOKEN_TTL = '7d';
export const DEFAULT_REFRESH_TOKEN_EXPIRES_IN_SECONDS = 7 * 24 * 60 * 60; // 604800 seconds
export const DEFAULT_JWT_ISSUER = 'teamtrack-auth';
export const DEFAULT_JWT_AUDIENCE = 'teamtrack-client';

// Phase 8: File Storage Constants
export const MAX_GENERAL_FILE_SIZE_BYTES = 104857600; // 100 MB
export const UPLOAD_INTENT_TTL_SECONDS = 900; // 15 minutes
export const DOWNLOAD_URL_TTL_SECONDS = 600; // 10 minutes

// Phase 14: Reliability, Observability & Performance Constants
export const DEFAULT_REQUEST_BODY_LIMIT = '1mb';
export const DEFAULT_SHUTDOWN_TIMEOUT_MS = 10000;
export const DEFAULT_DB_POOL_MAX = 20;
export const DEFAULT_DB_IDLE_TIMEOUT_MS = 30000;
export const DEFAULT_DB_CONNECTION_TIMEOUT_MS = 5000;
export const DEFAULT_DB_STATEMENT_TIMEOUT_MS = 30000;
export const DEFAULT_LOG_LEVEL = 'info';

export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  API_PORT: 'API_PORT',
  API_HOST: 'API_HOST',
  API_URL: 'API_URL',
  NEXT_PUBLIC_API_URL: 'NEXT_PUBLIC_API_URL',
  DATABASE_URL: 'DATABASE_URL',
  REDIS_URL: 'REDIS_URL',
  JWT_SECRET: 'JWT_SECRET',
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_TTL: 'ACCESS_TOKEN_TTL',
  REFRESH_TOKEN_TTL: 'REFRESH_TOKEN_TTL',
  ACCESS_TOKEN_ISSUER: 'ACCESS_TOKEN_ISSUER',
  ACCESS_TOKEN_AUDIENCE: 'ACCESS_TOKEN_AUDIENCE',
  COOKIE_SECURE: 'COOKIE_SECURE',
  COOKIE_SAME_SITE: 'COOKIE_SAME_SITE',
  CORS_ORIGIN: 'CORS_ORIGIN',
  RATE_LIMIT_ALLOW_MEMORY_FALLBACK: 'RATE_LIMIT_ALLOW_MEMORY_FALLBACK',
  STORAGE_DRIVER: 'STORAGE_DRIVER',
  S3_BUCKET: 'S3_BUCKET',
  S3_REGION: 'S3_REGION',
  S3_ENDPOINT: 'S3_ENDPOINT',
  S3_ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',
  S3_FORCE_PATH_STYLE: 'S3_FORCE_PATH_STYLE',
  STUN_SERVER: 'STUN_SERVER',
  TURN_SERVER: 'TURN_SERVER',
  LOG_LEVEL: 'LOG_LEVEL',
  LOG_FORMAT: 'LOG_FORMAT',
  DB_POOL_MAX: 'DB_POOL_MAX',
  DB_STATEMENT_TIMEOUT_MS: 'DB_STATEMENT_TIMEOUT_MS',
  SHUTDOWN_TIMEOUT_MS: 'SHUTDOWN_TIMEOUT_MS',
  REQUEST_BODY_LIMIT: 'REQUEST_BODY_LIMIT',
} as const;

export type EnvKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS];

