FROM node:22-alpine AS builder
WORKDIR /app

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Copy workspace descriptors
COPY package*.json ./
COPY tsconfig*.json ./

# Copy packages and web workspace
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/

# Install dependencies deterministically
RUN npm ci

# Build shared packages
RUN npm run build:packages

# Build the Next.js app (which uses standalone output based on next.config.js)
RUN npm run --workspace=@teamtrack/web build

# -------------------------
# Production Runner Stage
# -------------------------
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy the standalone output generated by Next.js
# It typically resides in apps/web/.next/standalone
# The standalone build includes minimal node_modules required for the app
COPY --from=builder /app/apps/web/public ./apps/web/public

# Set the correct permission for prerender cache
RUN mkdir -p /app/apps/web/.next && chown nextjs:nodejs /app/apps/web/.next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
# The standalone build outputs to `.next/standalone/` at the root of the app, 
# but because of monorepo, it mirrors the directory structure.
# So it's placed in `apps/web/.next/standalone/apps/web/server.js` or `apps/web/.next/standalone/server.js`.
# Next.js standalone in monorepo outputs relative to the repo root by default.
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Based on monorepo standalone output, the server file is located at apps/web/server.js
CMD ["node", "apps/web/server.js"]
